import { Tilemap } from '../classes/mapEl/map';
import { Tile, Floor, Wall, Lava } from '../classes/mapEl/tiles';

export const map1: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map2: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map3: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map4: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map5: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map6: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Lava(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Lava(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Lava(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map7: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map8: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map9: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];
export const map10: Tile[][] = [
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Floor(),
    new Wall(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Lava(),
    new Wall(),
    new Floor(),
    new Wall(),
  ],
  [
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
    new Wall(),
  ],
];

export const mapList: Tilemap[] = [
  new Tilemap(map1),
  new Tilemap(map2),
  new Tilemap(map3),
  new Tilemap(map4),
  new Tilemap(map5),
  new Tilemap(map6),
  new Tilemap(map7),
  new Tilemap(map8),
  new Tilemap(map9),
  new Tilemap(map10),
];
